name: Catch Quickee
favicon: null
layout_spectrum: 0.6499800365418196
typography_spectrum: 0.1905758730135858
title: Catch Quickee
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fef104'
    - '#00adf1'
    - '#c4996c'
    - '#010101'
    - '#e61e1f'
  brandStrength: 0.6875
  lightness: 0.43128787260502577
  saturation: 0.7923365905880928
  rhythmicContrast: 0.32761278725229204
purpose: []
