name: Catch Quickee
favicon: null
layout_spectrum: 0.6499800365418196
typography_spectrum: 0.1905758730135858
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.4123286462854594
  lightness: 0.43128787260502577
  saturation: 0.7923365905880928
  rhythmicContrast: 0.32761278725229204
purpose: []
