title: Catch Quickee
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
color:
  saturation: 0.6875
  brandStrength: 0.1326165
  lightness: 0.5
  brandColors:
    - '#fef104'
    - '#00adf1'
    - '#c4996c'
    - '#010101'
    - '#e61e1f'
  rhythmicContrast: 0.5
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: Catch Quickee
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.75881
layout_spectrum: 0.39047
